# from selenium import webdriver
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("https://practice.automationtesting.in/")
# driver.execute_script("window.scrollBy(0, 600);")
# Ruby = driver.find_element_by_css_selector('.post-160:nth-child(1) img')
# Ruby.click()
# REVIEWS = driver.find_element_by_class_name('reviews_tab')
# REVIEWS.click()
# Rating = driver.find_element_by_css_selector('.stars .star-5')
# Rating.click()
# Review = driver.find_element_by_id('comment')
# Review.send_keys('Nice book!')
# Name = driver.find_element_by_id('author')
# Name.send_keys('Anna')
# Email = driver.find_element_by_id('email')
# Email.send_keys('test@ya.ru')
# Submit = driver.find_element_by_id('submit')
# Submit.click()
# driver.quit()